---
- hosts: rocky
  tasks:
    - name: Installer Apache
      ansible.builtin.dnf:
        name=httpd state=present update_cache=true

    - name: Installer Php7
      ansible.builtin.dnf:
        name=php state=present

    - name: Démarrer le service Apache
      ansible.builtin.service:
        name=httpd state=started enabled=true

    - name: copier un phpinfo
      ansible.builtin.copy:
        src=info.php dest=/var/www/html/index.php owner=apache group=apache mode=0664
